global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape OTLP Collector's Prometheus exporter (host network)
  - job_name: "otel-collector"
    static_configs:
      - targets: ["127.0.0.1:8889"]

  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]

  # Scrape OTLP Collector internal metrics
  - job_name: "otel-collector-internal"
    static_configs:
      - targets: ["127.0.0.1:8888"]
